name: VS Code Dev + Ngrok Tunnel

on: [workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install code-server
        run: |
          sudo apt update
          sudo apt install -y curl unzip
          curl -fsSL https://code-server.dev/install.sh | sh
          mkdir -p ~/.config/code-server
          echo -e "bind-addr: 0.0.0.0:8080\nauth: password\npassword: vscode123\ncert: false" > ~/.config/code-server/config.yaml
          nohup code-server &> /dev/null &
          sleep 5

      - name: Install Ngrok and expose VS Code
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok

          ngrok config add-authtoken $NGROK_AUTH_TOKEN
          nohup ngrok http 8080 > ngrok.log &
          sleep 5
          cat ngrok.log

          echo "VS Code Dev Tunnel:"
          grep -o 'https://[a-z0-9.-]*\.ngrok.io' ngrok.log | head -n 1

      - name: Keep Alive
        run: sleep 21600
